resources/lang/sv/general.php, resources/lang/sv/levels.php, tests/TestCase.php
Hi! I added a Swedish localization for the project.
=> Swedish (sv) localization

resources/lang/es/general.php, resources/lang/es/levels.php, tests/TestCase.php
=> Spanish (es) localization

.scrutinizer.yml, .travis.yml, README.md, composer.json, resources/lang/nl/general.php, src/Commands/PublishCommand.php
=> Updating incorrect translation

README.md, _docs/3.Configuration.md, config/log-viewer.php, resources/lang/pt-BR/general.php, resources/lang/pt-BR/levels.php, tests/TestCase.php
Thank you for this awesome package =)
=> Added Brazilian Portuguese language

helpers.php, src/Entities/LogEntry.php
=> [Fix#43] Fixing the regex when the header has multiple datetimes

resources/views/show.blade.php
Replace newline char `\n` with `<br>`.
=> Format stack trace

resources/views/logs.blade.php
I love this LogViewer, but I missed the filter links on the amount.
I hope you that you merge my request, I personally think this is a nice update for your LogViewer.
=> Added filter links

helpers.php, src/Bases/Table.php, src/Contracts/LogLevelsInterface.php, src/Entities/LogEntry.php, src/Entities/LogEntryCollection.php, src/Providers/UtilitiesServiceProvider.php, src/Utilities/LogLevels.php, tests/Utilities/LogLevelsTest.php
=> Fixing the translation issue

config/log-viewer.php, src/Contracts/FactoryInterface.php, src/Contracts/FilesystemInterface.php, src/Contracts/LogViewerInterface.php, src/Contracts/Patternable.php, src/LogViewer.php, src/Providers/UtilitiesServiceProvider.php, src/Utilities/Factory.php, src/Utilities/Filesystem.php, tests/LogViewerTest.php, tests/Utilities/FactoryTest.php, tests/Utilities/FilesystemTest.php, tests/Utilities/LogCheckerTest.php, tests/fixtures/logs/laravel-cli-2015-01-01.log
=> Adding support to use a custom log files naming pattern

resources/lang/zh/general.php
=> [translate][zh] add logviewer::general.empty-logs

resources/lang/sv/general.php
Update for the Swedish translation
=> #95 update Swedish (sv) lang

resources/views/_template/master.blade.php, resources/views/dashboard.blade.php, resources/views/logs.blade.php, resources/views/show.blade.php, src/Contracts/LogViewer.php, src/Http/Controllers/Controller.php, src/Http/Controllers/LogViewerController.php, src/Tables/StatsTable.php, tests/Entities/LogCollectionTest.php, tests/Entities/LogEntryCollectionTest.php, tests/Entities/LogEntryTest.php, tests/Entities/LogTest.php, tests/Providers/CommandsServiceProviderTest.php, tests/Providers/UtilitiesServiceProviderTest.php, tests/Tables/StatsTableTest.php, tests/Utilities/FactoryTest.php, tests/Utilities/FilesystemTest.php, tests/Utilities/LogCheckerTest.php, tests/Utilities/LogLevelsTest.php, tests/Utilities/LogMenuTest.php, tests/Utilities/LogStylerTest.php
=> Updating dashboard (ChartJs v2)

resources/lang/tr/general.php, resources/lang/tr/levels.php
I complete missing translate, and I made a few small changes for intelligibility.
Reference #95 
Off topic: There is lot keywords on view files, hardcoded without use language files.
=> Complete the translations (tr)

resources/lang/zh-TW/general.php
Translate logviewer::general.empty-logs to zh-TW. 😄
=> Translate logviewer::general.empty-logs to zh-TW

resources/lang/id/general.php, resources/lang/id/levels.php, tests/TestCase.php
Add localization for Indonesia
=> Add localization for Indonesia

composer.json
This will make the package Support Auto-Discovery in Laravel 5.5
=> [L5.5] Support Auto-Discovery

resources/views/show.blade.php, src/Http/Controllers/LogViewerController.php
Use laravel collection "filter" method to achieve "search" feature. It may not efficient, just work. And I'm not good at CSS, hope someone can make it looker better.
=> [Front] Add search support (only the entry's header)

.travis.yml, composer.json, src/Http/Controllers/LogViewerController.php
=> [Fix #198] Fixing the pagination Base URL

resources/lang/ro/general.php
Added Romanian Translation for logviewer::general.empty-logs
=> Added Romanian Translation

_docs/1.Installation-and-Setup.md
=> ENV config for Laravel 5.5 and below

composer.json, src/Commands/ClearLogsCommand.php, src/LogViewer.php, src/Providers/CommandsServiceProvider.php, src/Utilities/Factory.php, tests/Commands/ClearLogsCommandTest.php, tests/Providers/CommandsServiceProviderTest.php, tests/TestCase.php
`php artisan log-viewer:clear` the command will clear/delete all the log files.
=> Feature clear all logs command

src/Tables/StatsTable.php, src/Utilities/LogLevels.php, tests/Utilities/LogLevelsTest.php
=> Fixing the Log Levels translations

resources/views/bootstrap-3/show.blade.php, resources/views/bootstrap-4/show.blade.php, src/Http/Controllers/LogViewerController.php, src/Utilities/LogChecker.php
=> Fixing the compact issue with missing variables

resources/views/bootstrap-3/show.blade.php, resources/views/bootstrap-4/show.blade.php
=> Adding the results count for the search form

_docs/1.Installation-and-Setup.md
=> Add version instruction to composer command

src/Utilities/LogChecker.php
=> Using the file name pattern from the filesystem (configurable)

.scrutinizer.yml, .travis.yml, README.md, _docs/0.Home.md, _docs/1.Installation-and-Setup.md, composer.json, src/Entities/Log.php, src/Entities/LogCollection.php, src/Entities/LogEntryCollection.php, src/Http/Controllers/LogViewerController.php, src/Utilities/Factory.php, tests/Entities/LogCollectionTest.php
+ Using the new LazyCollection to load the log files
=> Adding Laravel 6.0 support

src/LogViewerServiceProvider.php, src/Providers/RouteServiceProvider.php, src/Providers/ServicesProvider.php, src/Providers/UtilitiesServiceProvider.php, tests/LogViewerServiceProviderTest.php, tests/Providers/UtilitiesServiceProviderTest.php
=> Fixing the deferred provider

resources/views/bootstrap-3/show.blade.php, resources/views/bootstrap-4/show.blade.php
I have escaped the query input with double moustache braces so that the pages are not vulnerable to XSS attack.
Fixes: #301
=> Escape query input to prevent XSS

src/LogViewer.php
=> Fix LogViewer's version

.scrutinizer.yml, .travis.yml, resources/views/bootstrap-3/show.blade.php, resources/views/bootstrap-4/show.blade.php, src/Utilities/LogStyler.php
=> Adding PHP 7.4 support

resources/views/bootstrap-3/show.blade.php, resources/views/bootstrap-4/show.blade.php, src/Entities/LogEntry.php, tests/Entities/LogEntryTest.php
=> Parsing & displaying the log entry's context

.github/workflows/run-tests.yml, composer.json
- Updating composer dependencies
- Fixing github actions error
=> Updating the package

composer.json, config/log-viewer.php, views/bootstrap-5/_master.blade.php, views/bootstrap-5/dashboard.blade.php, views/bootstrap-5/logs.blade.php, views/bootstrap-5/show.blade.php
Closes: https://github.com/ARCANEDEV/LogViewer/issues/411
=> Adding bootstrap 5 template

.github/workflows/run-tests.yml, README.md, _docs/1.Installation-and-Setup.md, _docs/2.Configuration.md, composer.json, config/log-viewer.php
=> Adding Laravel v11 support
